### ISSUE TITLE
假如是_changes已经存在的key，然后把这个key =nil 不会触发newindex

### ISSUE THREAD

**Issue by uvtong** [cloudwu/tracedoc#3]
```lua
local tracedoc = require "tracedoc"

local doc = tracedoc.new {
	a = 1,
	b = { 1,2,3 },
	c = { d = 4 , e = 5 },
	d = {},
}

local function dump(doc)
	local changes = tracedoc.commit(doc, {})
	print("Dump:")
	for k,v in pairs(doc) do
		print(k,v)
		if type(v) == "table" then
			for k, v in pairs(v) do
				print("\t",k,v)
			end
		end
	end
	print("changes:")
	for k,v in pairs(changes) do
		print(k,v)
	end
end

dump(doc)

print "-----------------------------"

doc.c = 1
doc.c = nil

dump(doc)
```
这时候实际上还是c = { d = 4 , e = 5 }，并没有c=nil

**Comment by cloudwu** [comment]
谢谢，这里隐藏了一个结构性的 bug ，不只是上面的案例，还涉及其它一些情况，所以我重写了很多代码。

直接原因是：在 changes 集合里直接保存了修改的值，但是这个值是 nil 的话，会导致下次查询去查 last version 。所以最简单的改法是把 changes 的 index 方法从映射 last version 集合改为一个函数，这个函数来判断是否应该查询。查询条件是先判断 keys 里是否有修改过就可以了。

所以我增加了 `doc_read` 这个函数。

但有另一个类似的 bug 还没有解决：目前赋值一个新的 table 会在 `doc_change` 里转换成 tracedoc （没有放在 commit 里转换，是因为有可能在 commit 之前又把这个 table 读出去，会引发潜在问题）。如果对这个 key 连续赋值两次，第 2 次还是 table 时，无法触发 `doc_change` 方法，这样就行为不一致了。

综上，我重新写过后的流程变成了：

在 `doc_change` 里：

赋值一个 table 的话，如果 last version 是一个 tracedoc 就把这个 table 和老版本的 table 做替换（继续使用老的 table 对象，但数据换成新的）；否则，把 last version 先设置成一个空 trace doc ，再替换进数据。无论怎样，都不会把 key 记录在 keys 集合中。

赋值其它类型的对象，直接记录在 changes 表中，并把 key 登记在 keys 集合（表示这个 key 被修改）。

在 `doc_read` 里：

如果发现 keys 集合中登记过，说明上次 commit 到现在有修改过。而因为当前 changes 表没有这一项，所以一定是清为了 nil 。

如果 keys 集合中没有登记，直接返回 last version 中对应项。

迭代函数 `doc_next` 可以简化流程：

首先迭代 keys 集合中存在的项目，然后迭代 last version 中没有迭代过（不存在于 keys）中的项目。

commit 流程则是这样：

首先比对 keys 集合中存在的项目中，和 last version 对应值不同的项目。

然后递归 commit 所有子表，这里，所有的子表都一定不会在前一个步骤处理（因为 `doc_change` 中永远不会把子表登记在 keys 集合）。

**Comment by cloudwu** [comment]
今天继续改了一下：把 changes 的元方法移到 doc 中。

原来这里是想做一个优化：在 commit 后，修改的表项再次读写的话，尽量不触发函数调用。现在看来这个优化意义不大，不容易写对 。因为必须把右值为 table 的情况特殊处理。否则，如果先赋值一个普通值，再赋值 table ，就无法对 table 做转换了。

**Comment by uvtong** [comment]
@cloudwu  今天跑了一下，已经没问题了，perfert。   changes的index改成元方法之后，代码瞬间简单了很多。   ps. 云大晚上12点还在coding，我辈楷模，^_^。
